config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'frontend#index'
  get '/sobre-nosotros', to: 'frontend#about', as: 'about'
  get '/servicios/:permalink', to:'frontend#service', as: 'service_description'
  get '/trabaja-con-nosotros', to: 'frontend#contact', as: 'contact'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
  mount KepplerAdwords::Engine, at: '/', as: 'adwords'

  resources :admin, only: :index

  scope :admin do

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :services do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #Routing Blog

  #get '(*path)' => 'application#blog', :constraints => { :subdomain => 'http://blog.publinetecuador.com' }

  get '/blog' => redirect("/blog/")

end

app/models/service.rb
#Generado por keppler
require 'elasticsearch/model'
class Service < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  before_save :create_permalink
  validates_presence_of :name, :large_description, :short_description, :category
  validates_uniqueness_of :name
  validate :validates_category
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name, :short_description, :large_description, :category] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      short_description:  self.short_description.to_s,
      large_description:  self.large_description.to_s,
      category:  self.category.to_s
    }.as_json
  end

  def validates_category
    errors.add(:errors, "Debe seleccionar una categoría") unless (self.category == "Advisor") || (self.category == "Social") || (self.category == "Creativo")  
  end

  private

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

end
#Service.import

app/controllers/services_controller.rb
#Generado con Keppler.
class ServicesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    services = Service.searching(@query).all
    @objects, @total = services.page(@current_page), services.size
    redirect_to services_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  def destroy_multiple
    Service.destroy redefine_ids(params[:multiple_ids])
    redirect_to services_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:name, :permalink, :short_description, :large_description, :category)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/services/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to services_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @service do |f|
					.row
						= f.input :name, label:  t("model.#{controller_name.singularize}.attributes.name")
						= f.input :short_description, label:  t("model.#{controller_name.singularize}.attributes.short_description")
						= f.input :large_description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }
						= f.input :category, collection: ["Advisor", "Social", "Creativo"], label: false, include_blank: "Selecione una Categoría"

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/services/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Service
			= link_to edit_service_path(@service), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink"=>true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @service.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.category")
			.display-value= @service.category
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @service.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.short_description")
			.display-value= @service.short_description
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/services/_listing.html.haml
%tr{ id: "row-#{service.id}" }
	- if can? :destroy_multiple, Service
		%td.item-check{style:"width: 10%"}
			= link_to "", service_path(service), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{service.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{service.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{service.id}" }

		%td{style:"width: 30%"}
			= link_to "", service_path(service, search: @query), remote: true, class: "show-row"
			%span
				= service.name
		%td{style:"width: 30%"}
			= link_to "", service_path(service, search: @query), remote: true, class: "show-row"
			%span
				= service.short_description
								
	%td{style:"width: 5%"}		
		= link_to service_path(service), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/services/edit.html.haml
= title "Services - editar | #{@service.id}"
= render 'form'

app/views/services/index.html.haml
= title("Services - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_service_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", "data-no-turbolink" => true do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |service|
				= render 'listing', service: service
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado services.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_service_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/services/new.html.haml
= title "Services - Nuevo"
= render 'form'

app/views/services/show.html.haml
= title "Services | #{@service.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Service
				= link_to service_path(@service), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Service
				= link_to edit_service_path(@service), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to services_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @service.name.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.category")
					.display-value.fs-body-1.tc-black-2= @service.category.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.short_description")
					.display-value.fs-body-1.tc-black-2= @service.short_description.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.large_description")
					.display-value.fs-body-1.tc-black-2= @service.large_description.html_safe

app/views/services/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@service.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");