config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'frontend#index'
  get '/sobre-nosotros', to: 'frontend#about', as: 'about'
  get '/servicios/:permalink', to:'frontend#service', as: 'service_description'
  get '/trabaja-con-nosotros', to: 'frontend#contact', as: 'contact'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
  mount KepplerAdwords::Engine, at: '/', as: 'adwords'

  resources :admin, only: :index

  scope :admin do

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :services do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #Routing Blog

  #get '(*path)' => 'application#blog', :constraints => { :subdomain => 'http://blog.publinetecuador.com' }

  get '/blog' => redirect("/blog/")

end

app/models/client.rb
#Generado por keppler
require 'elasticsearch/model'
class Client < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :image, ImageUploader
  validates_presence_of :image, :name
  validates_uniqueness_of :name

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name
    }.as_json
  end

end
#Client.import

app/controllers/clients_controller.rb
#Generado con Keppler.
class ClientsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    clients = Client.searching(@query).all
    @objects, @total = clients.page(@current_page), clients.size
    redirect_to clients_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  def destroy_multiple
    Client.destroy redefine_ids(params[:multiple_ids])
    redirect_to clients_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :image)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/clients/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to clients_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @client do |f|
					.row
						= f.input :name, label:  t("model.#{controller_name.singularize}.attributes.name")
						= f.input :image, :as => :file_material, label: false, wrapper_html: { class: "file-field" }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/clients/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Client
			= link_to edit_client_path(@client), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @client.image, style: "width: 80%; margin-left: 10%; margin-top: 30px;"
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @client.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @client.name
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/clients/_listing.html.haml
%tr{ id: "row-#{client.id}" }
	- if can? :destroy_multiple, Client
		%td.item-check{style:"width: 10%"}
			= link_to "", client_path(client), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{client.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{client.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{client.id}" }

		%td{style:"width: 30%"}
			= link_to "", client_path(client, search: @query), remote: true, class: "show-row"
			%span
				= client.name
								
	%td{style:"width: 5%"}		
		= link_to client_path(client), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/clients/edit.html.haml
= title "Clients - editar | #{@client.id}"
= render 'form'

app/views/clients/index.html.haml
= title("Clients - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_client_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |client|
				= render 'listing', client: client
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado clients.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_client_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/clients/new.html.haml
= title "Clients - Nuevo"
= render 'form'

app/views/clients/show.html.haml
= title "Clients | #{@client.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Client
				= link_to client_path(@client), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Client
				= link_to edit_client_path(@client), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to clients_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card	
			.card-image
				= image_tag @client.image
			.card-content		
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.id")
						.display-value.fs-body-1.tc-black-2= @client.id.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @client.name.to_s.humanize

app/views/clients/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@client.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");