config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'frontend#index'
  get '/sobre-nosotros', to: 'frontend#about', as: 'about'
  get '/servicios/:permalink', to:'frontend#service', as: 'service_description'
  get '/trabaja-con-nosotros', to: 'frontend#contact', as: 'contact'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
  mount KepplerAdwords::Engine, at: '/', as: 'adwords'

  resources :admin, only: :index

  scope :admin do

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    resources :services do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end

  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #Routing Blog

  #get '(*path)' => 'application#blog', :constraints => { :subdomain => 'http://blog.publinetecuador.com' }

  get '/blog' => redirect("/blog/")

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'
	
  def index
  	@message = KepplerContactUs::Message.new
  	@advisors = Service.where category: "Advisor"
  	@sociales = Service.where category: "Social"
  	@creativos = Service.where category: "Creativo"
  end

  def about	
  	@message = KepplerContactUs::Message.new
  	@clients = Client.all
  end
  def service
  	@service = Service.find_by permalink: params[:permalink]
    @message = KepplerContactUs::Message.new
  end
  def contact
    @message = KepplerContactUs::Message.new
  end

end

app/views/layouts/frontend/_google_analytics.html.haml
- if Rails.env.production?
	:javascript
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-XXXXXXXX-X', 'auto');
		ga('send', 'pageview');

app/views/layouts/frontend/_head.html.haml
%head
	%meta{:name => "viewport", :content => "width=devise-width, initial-scale=0.8,maximum-scale=0.8,minimum-scale=0.8"}
	%link{:href => "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css", :rel => "stylesheet"}
	%link{:href => "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", :rel => "stylesheet"}
	%script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
	= stylesheet_link_tag 'frontend/application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'frontend/application', 'data-turbolinks-track' => true
	= render 'layouts/frontend/google_analytics'
	= favicon_link_tag "frontend/favicon.png"
	= csrf_meta_tags
	:javascript
		WebFontConfig = {
			google: { families: [  'Raleway::latin', 'Oswald:400,700:latin', 'Hind:400,500,600:latin' ] }
		};
		(function() {
			var wf = document.createElement('script');
			wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
				'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
			wf.type = 'text/javascript';
			wf.async = 'true';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(wf, s);
		})();

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/frontend/_navigation.html.haml
.navigator
	
	- if action_name == 'service'
		.arrow-back
			#arrow
				= image_tag('frontend/Landing/Flecha-Atras.png', id: "arrow-back", class: "animated pulse", style: "left: 10px;top: 10px;position: absolute;cursor: pointer;")

	%button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
		#menu
	%ul.dropdown-menu
		%li{class: "#{'activo' if action_name == 'index' }"}
			= link_to root_path do
				INICIO
		%li{class: "#{'activo' if action_name == 'about' }"}
			= link_to about_path do
				SOBRE NOSOTROS
		%li{class: "#{'activo' if action_name == 'service' }"}
			%a#nav SERVICIOS
		%li{class: "#{'activo' if action_name == 'contact' }"}
			= link_to contact_path do
				CONTACTOS

app/views/layouts/frontend/application.html.haml
!!!
%html
	= render 'layouts/frontend/head'
	%body
	%header
		= render 'layouts/frontend/navigation'
	%main{:role => "main"}
		= #render 'layouts/frontend/messages'
		= yield
	= render 'keppler_adwords/data'